version: '3.3'

services:
  backend:
    build:
      context: ./local-backend
    image: backend-dx_center
    container_name: backend-dx-center
    ports:
      - "8009:8009"
    volumes:
      - ./local-backend:/app
      - /app/node_modules
    restart: on-failure
    environment:
      - TZ=Asia/Bangkok